import React from 'react';
import { useLocale } from 'next-intl';
import Container from '@mui/material/Container';
import AppBar from '@/components/AppBar';
import Copyright from '@/components/Copyright';

export default function PrivacyPolicy() {
  const locale = useLocale();
  const dir = locale === 'en' ? 'ltr' : 'rtl';

  return (
    <div dir={dir} id="main">
      <AppBar dir={dir} />
      <Container>
        <h4 class="lead">Privacy Policy for app.rialir.com</h4>
        <p>
          If you require any more information or have any questions about our
          privacy policy, please feel free to contact us by email at
          info@rialir.com.
        </p>
        <br />
        <p>
          At app.rialir.com, the privacy of our visitors is of extreme
          importance to us. This privacy policy document outlines the types of
          personal information is received and collected by app.rialir.com and
          how it is used. Please note that this Policy may be amended from time
          to time and that any changes will be published here.
        </p>
        <h4>Log Files</h4>
        <p>
          Like many other Web sites, app.rialir.com makes use of log files. The
          information inside the log files includes internet protocol ( IP )
          addresses, type of browser, Internet Service Provider ( ISP ),
          date/time stamp, referring/exit pages, and number of clicks to analyze
          trends, administer the site, track user’s movement around the site,
          and gather demographic information. IP addresses, and other such
          information are not linked to any information that is personally
          identifiable.
        </p>
        <h4>Cookies and Web Beacons</h4>
        <p>
          app.rialir.com does use cookies to store information about visitors
          preferences, record user-specific information on which pages the user
          access or visit, customize Web page content based on visitors browser
          type or other information that the visitor sends via their browser.
          <br />
        </p>
        <h4>Cookies are used for the following purposes:</h4>
        <b>Settings within the Website</b>
        <p>
          These cookies are used to save your settings; allowing you to hide
          information boxes you have become familiar with, etc.
        </p>
        <b>Google Analytics &amp; Interest-Based Online Advertising</b>
        <p>
          This website uses Google Analytics. Google Analytics uses “cookies” to
          help us analyze how visitors use the site. The information collected
          includes the pages a visitor visits, the time a visit occurred,
          whether the visitor has been to the site before and what site referred
          the visitor to the web page. The information generated by the cookie
          about your use of the website will be transmitted to and stored by
          Google on servers in the United States. Google will use this
          information on behalf of app.rialir.com to evaluate your use of the
          website, compiling reports on website activity. We also use Google
          Analytics' 3 rd -party audience data, such as age, gender and
          interests to better understand the behavior of our customers and
          provide advertising targeted to suit your preferences and interests.
          For example, you may see ads on the Google Display Network, based on
          information collected through automated means (such as cookies).
          Automated technologies are used to collect information when you click
          on our ads, which helps track and manage the effectiveness of our
          marketing efforts. You can set preferences for how Google advertises
          to you using the{' '}
          <a target="_blank" href="https://www.google.com/settings/ads">
            Google Ad Preferences Page
          </a>{' '}
          and if you want you can opt out of interest-based advertising entirely
          by cookie settings or by using this{' '}
          <a target="_blank" href="https://tools.google.com/dlpage/gaoptout/">
            Google tool
          </a>{' '}
          .
        </p>
        <b>Remarketing on the Website and App</b>
        <p>
          Third party vendors, including Google, use cookies to serve ads based
          on a user's prior visits to app.rialir.com or other websites.
          <br />
          Google's use of advertising cookies enables it and its partners to
          serve ads to your users based on their visit to app.rialir.com and/or
          other sites on the Internet.
          <br />
          Users may opt out of personalized advertising by visiting{' '}
          <a target="_blank" href="https://www.google.com/settings/ads">
            Ads Settings
          </a>{' '}
          and other advertising service providers listed below.
          <br />
          You can turn off certain third party cookies for advertising purposes
          by visiting the Network Advertising Initiative, located here:{' '}
          <a target="_blank" href="http://www.networkadvertising.org/choices/">
            http://www.networkadvertising.org/choices/
          </a>{' '}
          or the DAA opt-out program, which are located here:{' '}
          <a target="_blank" href="http://www.aboutads.info/choices/">
            http://www.aboutads.info/choices/
          </a>
          , here (for EU/EEA citizens):{' '}
          <a target="_blank" href="http://www.youronlinechoices.eu/">
            http://www.youronlinechoices.eu/
          </a>{' '}
          and here (for mobile devices):{' '}
          <a target="_blank" href="http://www.aboutads.info/appchoices">
            http://www.aboutads.info/appchoices
          </a>
        </p>
        <p>
          Some of our advertising partners may use cookies and web beacons on
          our site. Our advertising partners include .... Google Adsense
        </p>
        <p>
          These third-party ad servers or ad networks use technology to the
          advertisements and links that appear on app.rialir.com send directly
          to your browsers. They automatically receive your IP address when this
          occurs. Other technologies ( such as cookies, JavaScript, or Web
          Beacons ) may also be used by the third-party ad networks to measure
          the effectiveness of their advertisements and / or to personalize the
          advertising content that you see. app.rialir.com has no access to or
          control over these cookies that are used by third-party advertisers.
          You should consult the respective privacy policies of these
          third-party ad servers for more detailed information on their
          practices as well as for instructions about how to opt-out of certain
          practices. app.rialir.com's privacy policy does not apply to, and we
          cannot control the activities of, such other advertisers or web sites.
          If you wish to disable cookies, you may do so through your individual
          browser options. More detailed information about cookie management
          with specific web browsers can be found at the browsers' respective
          websites.
        </p>
        <br />
        <h4>
          Third-party vendors and ad networks which serving ads on our mobile
          App:
        </h4>
        <div>
          <ul class="third-party">
            <li>
              <a
                target="_blank"
                href="https://policies.google.com/technologies/ads"
              >
                Google
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://liftoff.io/privacy-policy/">
                Liftoff
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.criteo.com/privacy">
                Criteo
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.oracle.com/legal/privacy/marketing-cloud-data-cloud-privacy-policy.html"
              >
                Oracle Data Cloud
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.evidon.com/resources/privacy-statement/"
              >
                Evidon
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.thetradedesk.com/general/privacy-policy"
              >
                The Trade Desk
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.trustarc.com/privacy-policy/"
              >
                TrustArc
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.integralads.com/privacy-policy"
              >
                Integral Ad Science
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.kochava.com/support-privacy/"
              >
                Kochava
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.nielsen.com/us/en/privacy-statement/digital-measurement.html"
              >
                Nielsen
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.adobe.com/privacy/general-data-protection-regulation.html"
              >
                Adobe Advertising Cloud
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.flashtalking.com/first-party-ad-serving/"
              >
                Flashtalking
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://createjs.com/legal/privacy.html">
                gskinner
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://adloox.com/disclaimer">
                Adloox
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.comscore.com/About-comScore/Privacy-Policy"
              >
                comScore
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.doubleverify.com/privacy/">
                DoubleVerify
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.kantarmedia.com/global/privacy-statement"
              >
                Kantar
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.valuedopinions.co.uk/privacy"
              >
                RN SSI Group
              </a>
              &nbsp;*
            </li>
          </ul>
        </div>

        <h4>
          Third-party vendors and ad networks which serving ads on our website
        </h4>
        <p>
          You may visit these websites (or alternatively by visiting:{' '}
          <a target="_blank" href="http://www.aboutads.info/choices/">
            www.aboutads.info
          </a>
          ) to opt out of the use of cookies for personalized advertising
        </p>
        <div>
          <ul class="third-party">
            <li>
              <a target="_blank" href="https://createjs.com/legal/privacy.html">
                gskinner
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201909010"
              >
                Amazon
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.appnexus.com/en/company/platform-privacy-policy"
              >
                AppNexus
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://fsharp.co/privacy-policy">
                F Sharp
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.tapcliq.com/privacy">
                tapCLIQ
              </a>
            </li>
            <li>
              <a target="_blank" href="https://virtualminds.de/datenschutz/">
                Virtual Minds
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.cloudflare.com/security-policy/"
              >
                Cloudflare
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.doubleverify.com/privacy/">
                DoubleVerify
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.evidon.com/resources/privacy-statement/"
              >
                Evidon
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.answermedia.com/privacy">
                Answer Media
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.criteo.com/privacy">
                Criteo
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://adloox.com/disclaimer">
                Adloox
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.oracle.com/legal/privacy/marketing-cloud-data-cloud-privacy-policy.html"
              >
                Oracle Data Cloud
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://site.adform.com/uncategorized/product-and-services-privacy-policy/"
              >
                Adform
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://batch.ba/datenschutzerklarung/">
                Batch Media
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.bannerflow.com/privacy">
                Bannerflow
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.integralads.com/privacy-policy"
              >
                Integral Ad Science
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.nielsen.com/us/en/privacy-statement/digital-measurement.html"
              >
                Nielsen
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.adventori.com/fr/avec-nous/mentions-legales/"
              >
                Adventori
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://platform161.com/cookie-and-privacy-policy/"
              >
                Platform161
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.sizmek.com/privacy-policy/">
                Sizmek
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.flashtalking.com/first-party-ad-serving/"
              >
                Flashtalking
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.conversantmedia.eu/legal/privacy-policy"
              >
                Conversant/CJ Affiliate
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.ebay.com/help/policies/member-behaviour-policies/user-privacy-notice-privacy-policy?id=4260#section12"
              >
                eBay
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.aunica.com.br/privacy/privacy.html"
              >
                Aunica
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://policies.oath.com/xw/en/oath/privacy/enterprise/b2bprivacypolicy/"
              >
                Oath
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.quantcast.com/privacy/">
                Quantcast
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.awin.com/de/rechtliches/privacy-policy"
              >
                Zanox
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.exactag.com/en/data-privacy">
                Exactag
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.otto.de/shoppages/service/datenschutz"
              >
                OTTO
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.reachgroup.com/en/privacy-statement/"
              >
                The Reach Group
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.commandersact.com/en/privacy/"
              >
                Commanders Act
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.trustarc.com/privacy-policy/"
              >
                TrustArc
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.akamai.com/compliance/privacy"
              >
                Akamai
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.comscore.com/About-comScore/Privacy-Policy"
              >
                comScore
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.mediamath.com/privacy-policy/"
              >
                MediaMath
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.adroll.com/gdpr">
                AdRoll, Inc.{' '}
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.meetrics.com/en/data-privacy/"
              >
                Meetrics
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.pixalate.com/privacypolicy/">
                Pixalate
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.sociomantic.com/privacy/en/">
                Sociomantic
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.ad4mat.com/en/privacy/">
                advanced STORE GmbH
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.kantarmedia.com/global/privacy-statement"
              >
                Kantar
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://green.erne.co/assets/PolicyCT.pdf"
              >
                Cloud Technologies
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.rtbhouse.com/gdpr/">
                RTB House
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.neory.com/privacy.html">
                NEORY GmbH
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.adobe.com/privacy/general-data-protection-regulation.html"
              >
                Adobe Advertising Cloud
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.unitymedia.de/privatkunden/datenschutz/"
              >
                Unitymedia
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://rakutenmarketing.com/legal-notices/services-privacy-policy"
              >
                Rakuten Marketing
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.groupm.com/privacy-policy">
                GroupM
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.affili.net/uk/footeritem/privacy-policy"
              >
                affilinet
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://admetrics.io/en/privacy_policy/">
                Admetrics
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.thetradedesk.com/general/privacy-policy"
              >
                The Trade Desk
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://ebuilders.nl/privacy">
                ebuilders
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.keycdn.com/gdpr">
                KeyCDN
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.whiteops.com/privacy">
                White Ops
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://adledge.com/data-privacy/">
                AdLedge
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://weborama.com/e-privacy/">
                Weborama
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.dma-institute.com/privacy-compliancy/"
              >
                DMA Institute
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://metapeople.com/datenschutz/">
                Metalyzer
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.lotame.com/about-lotame/privacy/"
              >
                Lotame
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://tripadvisor.mediaroom.com/us-privacy-policy"
              >
                TripAdvisor
              </a>
            </li>
            <li>
              <a target="_blank" href="https://relay42.com/privacy">
                Relay42
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.bidswitch.com/privacy-policy/"
              >
                IPONWEB
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.sojern.com/privacy/product-privacy-policy/"
              >
                Sojern
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://adara.com/2018/04/10/adara-gdpr-faq/"
              >
                Adara Media
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.mainad.com/privacy-policy">
                MainADV
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://impressiondesk.com/">
                Infectious Media
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.valuedopinions.co.uk/privacy"
              >
                RN SSI Group
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.scenestealer.tv/privacy-policy"
              >
                Scenestealer
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.webgains.com/public/en/privacy/"
              >
                Webgains
              </a>
            </li>
            <li>
              <a target="_blank" href="http://ads.1000mercis.com/us.html">
                numberly
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.emetriq.com/datenschutz/">
                emetriq
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.intelliad.de/datenschutz">
                intelliAd
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://c3metrics.com/privacy">
                C3 Metrics
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.amobee.com/trust/privacy-guidelines"
              >
                Amobee{' '}
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://privacy.audienceproject.com/for-users/"
              >
                AudienceProject
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.udg.de/wp-content/uploads/2018/04/privacy_policy_EN.pdf"
              >
                UDG
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://adserver01.de/">
                adnanny.com
              </a>
            </li>
            <li>
              <a target="_blank" href="http://www.jivox.com/privacy/">
                Jivox
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.roq.ad/privacy-policy">
                Roq.ad
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.hurra.com/impressum">
                hurra.com
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="#">
                De Persgroep Nederland B.V.
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.totaljobs.com/privacy-policy"
              >
                TotalJobs Group Ltd
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.publicismedia.de/datenschutz/"
              >
                Publicis Media
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.mindtake.com/en/reppublika-privacy-policy"
              >
                MindTake Research
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.usemax.de/?l=privacy">
                usemax (Emego GmbH)
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.awin.com/gb/legal/privacy-policy-gb"
              >
                Awin
              </a>
            </li>
            <li>
              <a target="_blank" href="https://crimtan.com/privacy-ctl/">
                Crimtan
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.beeswax.com/privacy.html">
                Beeswax
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://tealium.com/protecting-your-privacy-and-your-data/"
              >
                Tealium
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.atinternet.com/en/company/data-protection/"
              >
                AT Internet
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://ad.bsmartdata.com/privacy.php?lang=en"
              >
                BSmartData
              </a>
            </li>
            <li>
              <a target="_blank" href="http://www.semasio.com/privacy-policy/">
                Semasio GmbH
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.openx.com/legal/privacy-policy/"
              >
                OpenX Technologies
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.adspirit.de/datenschutz00.0.html"
              >
                AdSpirit AdServer
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="http://betting.geniussports.com/connextra-service-terms-conditions/"
              >
                Betgenius
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://advolution.de/privacy.php">
                advolution.control
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.admedo.com/privacy-policy">
                Admedo
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.yieldr.com/privacy/">
                Yieldr
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.wizaly.com/terms-of-use#privacy-policy"
              >
                Wizaly
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.tradedoubler.com/en/privacy-policy/"
              >
                Tradedoubler AB
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://rubiconproject.com/rubicon-project-yield-optimization-privacy-policy/"
              >
                Rubicon Project
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.constantcontact.com/legal/privacy-statement"
              >
                Constant Contact
              </a>
            </li>
            <li>
              <a target="_blank" href="https://web.neural.one/privacy-policy/">
                Neuralone
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.netflix.com/google-3PAS-info">
                Netflix
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.gsi-one.org/templates/gsi/en/files/privacy_policy.pdf"
              >
                GP One
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.belboon.com/en/about-us/datenschutz/"
              >
                Belboon
              </a>
            </li>
            <li>
              <a target="_blank" href="https://contactimpact.de/datenschutz">
                abilicom
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.parship.de/privacypolicy/">
                Parship
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.turbobytes.com/gdpr/">
                Turbobytes
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://pubmatic.com/legal/privacy-policy/"
              >
                PubMatic
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.audience2media.com/privacy">
                Audience2Media
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.home.neustar/privacy">
                Neustar
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://cablato.com/privacy">
                Cablato
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.protected.media/privacy-policy/"
              >
                Protected Media
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.maxcdn.com/gdpr/">
                MaxCDN
              </a>
            </li>
            <li>
              <a target="_blank" href="https://admixer.net/privacy">
                Admixer
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.xxxlutz.de/ocms/privacy">
                BDSK Handels GmbH &amp; Co. KG
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.iotecglobal.com/privacy-policy/"
              >
                IOTEC
              </a>
            </li>
            <li>
              <a target="_blank" href="http://avocet.io/privacy-portal">
                Avocet
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.salesforce.com/company/privacy/"
              >
                Salesforce DMP
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.objectivepartners.com/cookie-policy-and-privacy-statement/"
              >
                Objective Partners
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://adelement.com/privacy-policy.html"
              >
                AdElement
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://videologygroup.com/en/privacy-policy/"
              >
                Videology
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://site.msi-aci.com/Home/FlexTrackPrivacy"
              >
                MSI-ACI
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.dataxu.com/gdpr/">
                DataXu
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.simpli.fi/site-privacy-policy2/"
              >
                Simpli.fi
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.timeonegroup.com/privacy-policies/"
              >
                TimeOne
              </a>
            </li>
            <li>
              <a target="_blank" href="https://privacy.adtriba.com/">
                AdTriba
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.onetag.net/privacy/">
                OneTag
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.adriver.ru/about/privacy-en/"
              >
                Adriver
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.sfr.fr/securite-confidentialite.html"
              >
                SFR
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.bizible.com/gdpr">
                Bizible
              </a>
            </li>
            <li>
              <a target="_blank" href="https://sensic.net/">
                GfK
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.rhythmone.com/landing/gdpr">
                RhythmOne LLC
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.contentspread.net/?page=privacy"
              >
                media.ventive GmbH
              </a>
            </li>
            <li>
              <a target="_blank" href="https://clinch.co/pages/privacy.html">
                Clinch
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.nanointeractive.com/privacy">
                Nano Interactive
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.eulerian.com/en/privacy/">
                Eulerian Technologies
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://liveramp.com/service-privacy-policy/"
              >
                LiveRamp
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.vivalu.com/downloads/de_DE/VIVALU_Datenschutz_2018.pdf"
              >
                VIVALU{' '}
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.neodatagroup.com/en/security-policy"
              >
                Neodata Group
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.improvedigital.com/privacy-policy/"
              >
                Improve Digital
              </a>
            </li>
            <li>
              <a target="_blank" href="http://theadex.com">
                ADEX
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.emerse.com/privacy-policy/">
                Emerse
              </a>
            </li>
            <li>
              <a target="_blank" href="http://www.indexexchange.com/privacy/">
                Index Exchange
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://teads.tv/privacy-policy/">
                Teads
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.fyber.com/legal/gdpr-faqs/">
                Fyber
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.pulpo.com/en/privacy-policy/"
              >
                Pulpo (An Entravision Company)
              </a>
            </li>
            <li>
              <a
                target="_blank"
                href="https://nugg.ad/de/datenschutz/allgemeine-informationen.html"
              >
                nugg.ad
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.spotx.tv/privacy-policy/">
                SpotX
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://exponential.com/privacy/">
                Exponential
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.metrixlab.com/privacy-statement/"
              >
                Macromill group
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://www.rackspace.com/gdpr">
                Rackspace
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.ve.com/privacy-policy">
                Ve Interactive
              </a>
            </li>
            <li>
              <a target="_blank" href="http://bombora.com/privacy">
                Bombora
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="http://optomaton.com/privacy.html">
                Optomaton
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.perfectaudience.com/privacy/"
              >
                Perfect Audience
              </a>
            </li>
            <li>
              <a target="_blank" href="https://adclouds.io/data-gdpr/">
                Adclouds
              </a>
            </li>
            <li>
              <a target="_blank" href="https://zms.zalando.com/#">
                ZMS
              </a>
              &nbsp;*
            </li>
            <li>
              <a target="_blank" href="https://www.arrivalist.com/privacy#gdpr">
                Arrivalist
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.combell.com/nl/over-combell/privacy-policy"
              >
                Combell
              </a>
            </li>
            <li>
              <a target="_blank" href="https://privacy.mbr-targeting.com">
                MBR Targeting Gmbh
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="https://www.effiliation.com/politique-confidentialite.html"
              >
                Effinity
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://smadex.com/end-user-privacy-policy/"
              >
                Smadex
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://static.tabmo.io.s3.amazonaws.com/privacy-policy/index.html"
              >
                TabMo
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.admaxim.com/admaxim-privacy-policy/"
              >
                AdMaxim
              </a>
              &nbsp;*
            </li>
            <li>
              <a
                target="_blank"
                href="http://www.ibillboard.com/privacymanagement/"
              >
                iBILLBOARD
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.knorex.com/privacy">
                Knorex
              </a>
            </li>
            <li>
              <a target="_blank" href="https://www.mp-newmedia.com/datenschutz">
                M,P,NEWMEDIA,
              </a>
            </li>
          </ul>
        </div>
      </Container>
      <Copyright />
    </div>
  );
}
